#!/bin/bash
#
# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Push a new version of the docs.

if [[ "${TRAVIS_BRANCH}" == "master" ]] && \
     [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  ghp-import -n docs/_build/html
  git push -fq https://${GH_OAUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
fi
